name: Sync to Bakery Repos

on:
  workflow_dispatch: # Manual trigger

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bakerymain (Full Clone)  
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Authenticate with SSH
        run: ssh -T git@github.com || true  

      - name: Push changes to mdsbakery
        run: |
          git remote remove mdsbakery || true
          git remote add mdsbakery git@github.com:Nijaa66/Mdsbakery.git
          git push --force mdsbakery main

      - name: Push changes to tejusbakery
        run: |
          git remote remove tejusbakery || true
          git remote add tejusbakery git@github.com:Nijaa66/TejusBakery.git
          git push --force tejusbakery main
