name: Create a Comment on Issue

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    name: Issue Comment Job  # This will be displayed in workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
