name: create a comment on issue 

on:
  issues:
    types:[opend]  

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: dump-github-context
        run:echo'${{to JSON(hithub.event)}}' | jq 
        shell: bash

 
