name: "Create a Comment on Issue"

on:
  issues:
    types: [opened]

run-name: "Issue Comment Job by Nijaa"

jobs:
  comment-on-issue:
    name: "Issue Comment Job"  # This will be displayed in workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** ✨
            - Created by [create-or-update-comment][1]
          reactions: '+1'
