name: create a comment on issue

on:
  issues:
    types: [opened]  # Fixed typo and added space

jobs:
  comment-on-issue:
    name:default-name
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo '${{ toJSON(github.event) }}' | jq  # Fixed syntax
        shell: bash
