name: hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hi, this is the first YAML file by Nijaa"
        shell: bash

  mysecondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: My Second Job
        run: echo "This is my second job by Nijaa"
        shell: bash
